//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Exercise11.2
//  @ File Name : Person.java
//  @ Date : 2014/5/27
//  @ Author : Copperfield
//
//




public class Person {
	protected String name;
	protected String address;
	protected String phone;
	protected String email;
	public Person() {
	
	}
	
	public Person(String name, String address, String phone, String email) {
	    this.name = name;
	    this.address = address;
	    this.phone = phone;
	    this.email = email;
	}
	
	public String getName() {
	    return name;
	}
	
	public void setName(String name) {
	    this.name = name;
	}
	
	public String getAddress() {
	    return address;
	}
	
	public void setAddress(String address) {
	    this.address = address;
	}
	
	public String getPhone() {
	    return phone;
	}
	
	public void setPhone(String phone) {
	    this.phone = phone;
	}
	
	public String getEmail() {
	    return email;
	}
	
	public void setEmail(String email) {
	    this.email = email;
	}
	
	public String toString() {
	    return "Person " + name;
	}
}
