//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 11.3
//  @ File Name : CheckingAccount.java
//  @ Date : 2014/5/28
//  @ Author : Copperfield
//
//




public class CheckingAccount extends Account {
	protected double overdraftLimit = 5000;
	public String toString() {
	    return "CheckingAccount";
	}
}
