//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 10.1
//  @ File Name : Time.java
//  @ Date : 2014/5/6
//  @ Author : Copperfield
//
//




public class Time {
	private int hour;
	private int minute;
	private int second;
	
	public Time() {
	    this(System.currentTimeMillis());
	}

	public Time(long elapseTime) {
	    long totalSeconds = elapseTime / 1000;

        second = (int)(totalSeconds % 60);

        long totalMinutes = totalSeconds / 60;

        minute = (int)(totalMinutes % 60);

        int totalHours = (int)(totalMinutes / 60);

        hour = (int)(totalHours % 24);
	}

	public Time(int newHour, int newMinute, int newSecond) {
	    second = newSecond;
	    minute = newMinute;
	    hour = newHour;
	}
	
	public int getHour() {
	    return hour;
	}
	
	public int getMinute() {
	    return minute;
	}
	
	public int getSecond() {
	    return second;
	}
	
	public void setTime(long elapseTime) {
	    long totalSeconds = elapseTime / 1000;

        second = (int)(totalSeconds % 60);

        long totalMinutes = totalSeconds / 60;

        minute = (int)(totalMinutes % 60);

        int totalHours = (int)(totalMinutes / 60);

        hour = (int)(totalHours % 24);
	}
}
