//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 8.7
//  @ File Name : Account.java
//  @ Date : 2014/4/29
//  @ Author : Copperfield
//
//
import java.util.*;

public class Account {
	private int id = 1;
	private String name;
	private double balance = 0;
	private static double annualInterestRate = 0;
	private Date dateCreated;
	private ArrayList transaction = new ArrayList();

	public Account() {
		dateCreated = new Date();
	}

	public Account(int id, String name, double balance) {
		this.id = id;
		this.name = name;
		this.balance = balance;
		dateCreated = new Date();
	}
		
	public int getId() {
	    return id;
	}
	
	public void setId(int newId) {
	    if (newId >= 0)
	    	id = newId;
	}
	
    public String getName() {
    	return name;
    }

	public double getBalance() {
	    return balance;
	}
	
	public void setBalance(double newBalance) {
	    if (newBalance >= 0)
	        balance = newBalance;
	}
	
	public static double getAnnualInterestRate() {
	    return annualInterestRate / 100;
	}
	
	public static void setAnnualInterestRate(double newAnnualInterestRate) {
	    if (newAnnualInterestRate >= 0)
	    	annualInterestRate = newAnnualInterestRate;
	}
	
	public String getDateCreated() {
	    dateCreated = new Date();
	    return dateCreated.toString();
	}
	
	public double getMonthlyInterestRate() {
	    return annualInterestRate / 1200;
	}

	public ArrayList getTransactions() {
		return transaction;
	}
	
	public void withdraw(double money) {
		balance -= money;
	    transaction.add(new Transaction('W', money, balance, "withdraw " + money + " dollars"));
	}
	
	public void deposit(double money) {
		balance += money;
	    transaction.add(new Transaction('D', money, balance, "deposit " + money + " dollars"));
    }
}

class Transaction {
	private Date date;
	private char type;
	private double amount;
	private double balance;
	private String description;

	public Transaction(char type, double amount, double balance, String description) {
		date = new Date();
		this.type = type;
		this.amount = amount;
		this.balance = balance;
		this.description = description;
	}

	public Date getDate() {
		return date;
	}

	public char getType() {
		return type;
	}

	public double getAmount() {
		return amount;
	}

	public double getBalance() {
		return balance;
	}

	public String getDescription() {
		return description;
	}
}