//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Stock.java
//  @ Date : 2014/4/29
//  @ Author : 
//
//


public class Stock {
	String symbol;
	String name;
	double previousClosingPrice;
	double currentPrice;
	
	public Stock(String newSymbol, String newName) {
	    symbol = newSymbol;
	    name = newName;
	}
	
	public double getChangePercent() {
	    return (currentPrice - previousClosingPrice) / 
	        previousClosingPrice;
	}
}
