//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 10.14
//  @ File Name : MyData.java
//  @ Date : 2014/5/11
//  @ Author : Copperfield
//
//


import java.util.*;

public class MyDate {
	private int year;
	private int month;
	private int day;
	public MyDate() {
	    Calendar date = Calendar.getInstance();
	    year = date.get(Calendar.YEAR);
	    month = date.get(Calendar.MONTH);
	    day = date.get(Calendar.DATE);
	}

	public MyDate(int year, int month, int day) {
	    this.year = year;
	    this.month = month;
	    this.day = day;
	}
	
	public int getYear() {
	    return year;
	}
	
	public int getMonth() {
	    return month;
	}
	
	public int getDay() {
	    return day;
	}
}
