//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Exercise11.2
//  @ File Name : Student.java
//  @ Date : 2014/5/27
//  @ Author : Copperfield
//
//




public class Student extends Person {
	public static int FRESHMAN = 0;
	public static int SOPHOMORE = 1;
	public static int JUNIOR = 2;
	public static int SENIOR = 3;
	protected int status = FRESHMAN;
	public Student() {
	
	}
	
	public Student(int status) {
	    this.status = status;
	}
	
	public int getStatus() {
	    return status;
	}
	
	public void setStatus(int status) {
	    this.status = status;
	}
	
	public String toString() {
	    return "Student " + name;
	}
}
