//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 11.3
//  @ File Name : SavingAccount.java
//  @ Date : 2014/5/28
//  @ Author : Copperfield
//
//




public class SavingAccount extends Account {
	public String toString() {
	    return "SavingAccount";
	}
}
