//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 8.8
//  @ File Name : Fan.java
//  @ Date : 2014/4/29
//  @ Author : Copperfield
//
//




public class Fan {
	final static int SLOW = 1;
	final static int MEDIUM = 2;
	final static int FAST = 3;
	private int speed = SLOW;
	private boolean on = false;
	private double radius = 5;
	public String color = "blue";
	public Fan() {
	}
	
	public String getSpeed() {
	    switch (speed) {
	    	case 1: return "SLOW";
	    	case 2: return "MEDIUM";
	    	case 3: return "FAST";
	    	default: return null;
	    }
	}
	
	public void setSpeed(int newSpeed) {
	    if (newSpeed >= 1 && newSpeed <= 3)
	    	speed = newSpeed;
	}
	
	public boolean getOn() {
	    return on;
	}
	
	public void setOn(boolean newOn) {
	    on = newOn;
	}
	
	public double getRadius() {
	    return radius;
	}
	
	public void setRadius(double newRadius) {
	    if (newRadius >= 0)
	    	radius = newRadius;
	}
	
	public String getColor() {
	    return color;
	}
	
	public void setColor(String newColor) {
	    color = newColor;
	}
	
	public String toString() {
	    if (on) {
	    	StringBuilder string = new StringBuilder();
	    	string.append("Speed: " + speed + "\n");
	    	string.append("Color: " + color + "\n");
	    	string.append("Radius: " + radius + "\n");
	    	return (string.toString());
	    }
	    else return "fan is off";
	}
}
