//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 11.3
//  @ File Name : Account.java
//  @ Date : 2014/4/29
//  @ Author : Copperfield
//
//
import java.util.Date;

public class Account {
	protected int id = 1;
	protected double balance = 0;
	protected double annualInterestRate = 0;
	protected Date dateCreated;
	public Account() {
	}
	
	public Account(int newId, double newBalance) {
	    id = newId;
	    balance = newBalance;
	}
	
	public int getId() {
	    return id;
	}
	
	public void setId(int newId) {
	    if (newId >= 0)
	    	id = newId;
	}
	
	public double getBalance() {
	    return balance;
	}
	
	public void setBalance(double newBalance) {
	    if (newBalance >= 0)
	        balance = newBalance;
	}
	
	public double getAnnualInterestRate() {
	    return annualInterestRate / 100;
	}
	
	public void setAnnualInterestRate(double newAnnualInterestRate) {
	    if (newAnnualInterestRate >= 0)
	    	annualInterestRate = newAnnualInterestRate;
	}
	
	public String getDateCreated() {
	    dateCreated = new Date();
	    return dateCreated.toString();
	}
	
	public double getMonthlyInterestRate() {
	    return annualInterestRate / 1200;
	}
	
	public void withdraw(double money) {
	    if (balance > money)
	    	balance = balance - money;
	}
	
	public void deposit(double money) {
	    balance = balance + money;
	}
}
