//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 10.11
//  @ File Name : Circle2D.java
//  @ Date : 2014/5/8
//  @ Author : Copperfield
//
//




public class Circle2D {
	private double x;
	private double y;
	private double radius;
	public Circle2D() {
	    this(0, 0, 1);
	}
	
	public Circle2D(double x, double y, double radius) {
	    this.x = x;
	    this.y = y;
	    this.radius = radius;
	}
	
	public double getX() {
	    return x;
	}
	
	public double getY() {
	    return y;
	}
	
	public double getRadius() {
	    return radius;
	}
	
	public double getArea() {
	    return Math.PI * radius * radius;
	}
	
	public double getPerimeter() {
	    return Math.PI * 2 * radius;
	}
	
	public boolean contains(double x, double y) {
	    double d = distance(this.x, this.y, x, y);
	    return d < radius;
	}
	
	public boolean contains(Circle2D circle) {
	    double d = distance(this.x, this.y, circle.x, circle.y);
	    return d < Math.abs(this.radius - circle.radius);
	}
	
	public boolean overlaps(Circle2D circle) {
	    double d = distance(this.x, this.y, circle.x, circle.y);
	    return d > Math.abs(this.radius - circle.radius) &&
	           d < (this.radius + circle.radius);
	}

	private static double distance(double x1, double y1, 
        double x2, double y2) {
        return Math.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2));
    }
}
