//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 10.8
//  @ File Name : Tax.java
//  @ Date : 2014/5/9
//  @ Author : Copperfield
//
//




public class Tax {
	private int filingStatus = SINGLE_FILER;
	public final static int SINGLE_FILER = 0;
	public final static int MARRIED_JOINTLY = 1;
	public final static int MARRIED_SEPARATELY = 2;
	public final static int HEAD_OF_HOUSEHOLD = 3;
	private int[][] brackets = {
        {27050, 65550, 136750, 297350}, // Single filer
        {45200, 109250, 166500, 297350}, // married filing jointly
        {22600, 54625, 83250, 148675}, // married filing separately
        {36250, 93650, 151650, 297350} // head of household
	};
	private double[] rates = {0.10, 0.15, 0.25, 0.28, 0.33, 0.35};
	public double taxableIncome = 100000;
	public Tax() {
	   
	}
	
	public Tax(int filingStatus, int[][] brackets, double[] rates, double taxableIncome) {
	    this.filingStatus = filingStatus;
	    this.brackets = brackets;
	    this.rates = rates;
	    this.taxableIncome = taxableIncome;
	}
	
	public int getFilingStatus() {
	    return filingStatus;
	}
	
	public void setFilingStatus(int status) {
	    filingStatus = status;
	}
	
	public int[][] getBrackets() {
	    return brackets;
	}
	
	public void setBrackets(int[][] brackets) {
	    this.brackets = brackets;
	}
	
	public double[] getRates() {
	    return rates;
	}
	
	public void setRates(double[] rates) {
	    this.rates = rates;
	}
	
	public double getTaxableIncome() {
	    return taxableIncome;
	}
	
	public void setTaxableIncome(double taxableIncome) {
	    this.taxableIncome = taxableIncome;
	}
	
	public double getTax() {
		double tax;
	    if (taxableIncome <= brackets[filingStatus][0])
			tax = taxableIncome * rates[0]; // Done
		else {
			tax = brackets[filingStatus][0] * rates[0];
			for (int i = 1; i < brackets[filingStatus].length; i++) {
		        if (taxableIncome > brackets[filingStatus][i]) 
		        	tax += (brackets[filingStatus][i] - brackets[filingStatus][i - 1]) * rates[i];
		    	else {
		    		tax += (taxableIncome - brackets[filingStatus][i - 1]) * rates[i];
		            break;
		    	}
			}		
		}

		if (taxableIncome > brackets[filingStatus][3])
			tax += (taxableIncome - brackets[filingStatus][3]) * rates[5];
        
        return tax;
	}
}
