//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 10.3
//  @ File Name : MyInteger.java
//  @ Date : 2014/5/6
//  @ Author : Copperfield
//
//




public class MyInteger {
	private int value;

	public MyInteger(int value) {
	    this.value = value;
	}
	
	public int getValue() {
	    return value;
	}
	
	public boolean isEven() {
	    return isEven(value);
	}

	public static boolean isEven(int value) {
	    if (value % 2 == 0)
	    	return true;
	    else 
	    	return false;
	}

    public static boolean isEven(MyInteger value) {
	    return isEven(value.getValue());
	}

	public boolean isOdd() {
	    return isOdd(value);
	}

	public static boolean isOdd(int value) {
	    if (value % 2 == 1)
	    	return true;
	    else
	    	return false;
	}

	public static boolean isOdd(MyInteger value) {
	    return isOdd(value.getValue());
	}
	
	public boolean isPrime() {
	    return isPrime(value);
	}
	
	public static boolean isPrime(int value) {
	    if ((value == 1) || (value == 2)) {
            return true;
        }

	    for (int divisor = 2; divisor <= value / 2; divisor++) {
	    	if (value % divisor == 0)
	    		return false;
	    }

	    return true;
	}
	
	public static boolean isPrime(MyInteger value) {
	    return isPrime(value.getValue());
	}
	
	public boolean equals(int value) {
	    if (this.value == value)
	    	return true;
	    else
	    	return false;
	}
	
	public boolean equals(MyInteger value) {
	    if (value.equals(this.value))
	        return true;
	    else 
	        return false;   	
	}
	
	public static int parseInt(char[] numbers) {
	    int number = 0;
        for (int i = 0; i < numbers.length; i++) {
        	number = number * 10 + (numbers[i] - '0');
        }
        return number;
	}
	
	public static int parseInt(String numbers) {
	    int number = 0;
	    for (int i = 0; i < numbers.length(); i++) {
	    	number = number * 10 + (numbers.charAt(i) - '0');
	    }
	    return number;
	}
}
