//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 8.9
//  @ File Name : RegularPolygon.java
//  @ Date : 2014/4/30
//  @ Author : Copperfield
//
//




public class RegularPolygon {
	private int n = 3;
	private double side = 1;
	private double x = 0;
	private double y = 0;
	public RegularPolygon() {
	}
	
	public RegularPolygon(int newN, double newSide) {
	    n = newN;
	    side = newSide;
	    x = 0;
	    y = 0;
	}
	
	public RegularPolygon(int newN, double newSide, double newX, double newY) {
	    n = newN;
	    side = newSide;
	    x = newX;
	    y = newY;
	}
	
	public int getN() {
	    return n;
	}
	
	public void setN(int newN) {
	    if (newN >= 3)
	    	n = newN;
	}
	
	public double getSide() {
	    return side;
	}
	
	public void setSide(double newSide) {
	    if (newSide > 0)
	    	side = newSide;
	}
	
	public double getX() {
	    return x;
	}
	
	public void setX(double newX) {
	    x = newX;
	}
	
	public double getY() {
	    return y;
	}
	
	public void setY(double newY) {
	    y = newY;
	}
	
	public double getPerimeter() {
	    return n * side;
	}
	
	public double getArea() {
	    return n * side * side / Math.tan(Math.PI / n) / 4;
	}
}
