//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Exercise11.2
//  @ File Name : Employee.java
//  @ Date : 2014/5/27
//  @ Author : Copperfield
//
//




public class Employee extends Person {
	protected String office;
	protected double salary;
	protected MyDate datesOfEmployment;
	public Employee() {
	
	}
	
	public Employee(String office, double salary, MyDate datesOfEmployment) {
	    this.office = office;
	    this.salary = salary;
	    this.datesOfEmployment = datesOfEmployment;
	}
	
	public String getOffice() {
	    return office;
	}
	
	public void setOffice(String office) {
	    this.office = office;
	}
	
	public double getSalary() {
	    return salary;
	}
	
	public void setSalary(double salary) {
	    this.salary = salary;
	}
	
	public MyDate getDateOfEmployment() {
	    return datesOfEmployment;
	}
	
	public String toString() {
	    return "Employee " + name;
	}
}
