//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Exercise11.2
//  @ File Name : Faculty.java
//  @ Date : 2014/5/27
//  @ Author : Copperfield
//
//




public class Faculty extends Employee {
	public static int LECTURER = 0;
	public static int ASSISTANT_PROFESSOR = 1;
	public static int ASSOCIATE_PROFESSOR = 2;
	public static int PROFESSOR = 3;
	protected String officeHours;
	protected int rank;
	public String toString() {
	    return "Faculty " + name;
	}
}
