//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Exercise11.2
//  @ File Name : Staff.java
//  @ Date : 2014/5/27
//  @ Author : Copperfield
//
//




public class Staff extends Employee {
	protected Object title;
	public String toString() {
	    return "Staff " + name;
	}
}
